/* tslint:disable */
/* eslint-disable */
/**
 * Rgr
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { JobRequest } from './job-request';

/**
 * 
 * @export
 * @interface Client
 */
export interface Client {
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    'surname': string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    'middleName': string;
    /**
     * 
     * @type {number}
     * @memberof Client
     */
    'registryNumber': number;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    'gender': string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    'receiptNumber': string;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    'phone': string;
    /**
     * 
     * @type {Array<JobRequest>}
     * @memberof Client
     */
    'clientsRequests'?: Array<JobRequest> | null;
}

