/* tslint:disable */
/* eslint-disable */
/**
 * Rgr
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JobRequest
 */
export interface JobRequest {
    /**
     * 
     * @type {string}
     * @memberof JobRequest
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobRequest
     */
    'positionName': string;
    /**
     * 
     * @type {number}
     * @memberof JobRequest
     */
    'salary': number;
}

