/* tslint:disable */
/* eslint-disable */
/**
 * Rgr
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OwnerShipType } from './owner-ship-type';

/**
 * 
 * @export
 * @interface ModifyEmployerDto
 */
export interface ModifyEmployerDto {
    /**
     * 
     * @type {string}
     * @memberof ModifyEmployerDto
     */
    'name': string;
    /**
     * 
     * @type {OwnerShipType}
     * @memberof ModifyEmployerDto
     */
    'ownerShipType': OwnerShipType;
    /**
     * 
     * @type {number}
     * @memberof ModifyEmployerDto
     */
    'registryNumber': number;
    /**
     * 
     * @type {string}
     * @memberof ModifyEmployerDto
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof ModifyEmployerDto
     */
    'phone': string;
}

