/* tslint:disable */
/* eslint-disable */
/**
 * Rgr
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModifyClientDto
 */
export interface ModifyClientDto {
    /**
     * 
     * @type {string}
     * @memberof ModifyClientDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ModifyClientDto
     */
    'surname': string;
    /**
     * 
     * @type {string}
     * @memberof ModifyClientDto
     */
    'middleName': string;
    /**
     * 
     * @type {number}
     * @memberof ModifyClientDto
     */
    'registryNumber': number;
    /**
     * 
     * @type {string}
     * @memberof ModifyClientDto
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof ModifyClientDto
     */
    'gender': string;
    /**
     * 
     * @type {string}
     * @memberof ModifyClientDto
     */
    'receiptNumber': string;
    /**
     * 
     * @type {string}
     * @memberof ModifyClientDto
     */
    'phone': string;
}

